#!/bin/bash

session="Heater"

cd /home/pi/HeatControl

# Check if the session exists, discarding output
# We can check $? for the exit status (zero for success, non-zero for failure)
# tmux has-session -t $session 2>/dev/null

tmux kill-session -t $session
tmux new-session -d -s $session 'sudo python3 main.py'

# Attach to created session
tmux attach-session -t $session
