# This is a template config file for the heatcontrol server.
# Copy in home directory (~) on computer where gui runs and
# rename file to '.heat_control_ssh.yml'

host: 'TODO specify'        # Name of server where heater runs on
port: 22                    # SSH port on server to connect to. Default 22
username: 'TODO specify'    # Username to authenticate as
password: 'TODO specify'    # Password used for authentication